name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./short-link-gen
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Start server
        run: |
          npm start &
          sleep 20 # Increase sleep time to ensure the server has enough time to start
          curl -v http://localhost:3000
      - name: Check server status
        run: curl -v http://localhost:3000
      - name: Run Tests
        run: npm run test
