name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    services:
      web:
        image: node:18.19.0
        ports:
          - 3000:3000
        options: >-
          --health-cmd="curl --fail http://localhost:3000 || exit 1"
          --health-interval=30s
          --health-timeout=30s
          --health-retries=10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'
      - name: Install dependencies
        run: npm install
        working-directory: ./short-link-gen
      - name: Start server
        run: |
          npm run build
          npm start &
          sleep 10
          curl -v http://localhost:3000
        working-directory: ./short-link-gen
      - name: Wait for server to be ready
        run: sleep 60
      - name: Run Tests
        run: npm test
        working-directory: ./short-link-gen
