name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'
      - name: Install dependencies
        run: npm install
        working-directory: ./short-link-gen
      - name: Build project
        run: |
          npm run dev
        working-directory: ./short-link-gen
      - name: Start server
        run: |
          npm start
        working-directory: ./short-link-gen
      - name: Run Tests
        run: npm run test
        working-directory: ./short-link-gen
